---
abstract: 'Turn WGS84 coordinates into three words or OneWords and vice-versa using w3w.co HTTP API'
author:
  - 'mtmail <mtmail-cpan@gmx.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-What3Words
provides:
  Geo::What3Words:
    file: lib/Geo/What3Words.pm
    version: v1.0.6
requires:
  Data::Dumper: '0'
  JSON: '2'
  LWP::UserAgent: '0'
  List::Util: '0'
  Net::Ping: '0'
  Net::Ping::External: '0'
  Test::Exception: '0'
  Test::LWP::Recorder: '0'
  Test::More: '0.88'
  URI: '0'
  perl: '5.010'
resources:
  repository: https://github.com/lokku/perl-Geo-What3Words.git
version: 1.0.6
